baseURL: "https://nithinvyasportfolio.netlify.app/"
languageCode: en-us
title: Nithin Vyas
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: education
      name: Education
      url: /education
      weight: 25
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 20
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: tags
      name: Skills
      url: /skills
      weight: 40
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Nithin Vyas"
    subtitle: Hi, I'm Nithin Vyas Ravipati, a Data Enthusiast pursuing an MS in Data Analytics Engineering at Northeastern University. I transform data into insights, specializing in SQL, Python and Tableau. Join me on LinkedIn, and let's unlock the potential of data together!

    imageUrl: "home/mypic.png"
    imageWidth: 220
    imageHeight: 220
    buttons:
      # - name: Resume
      #   url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:nithinvyas18@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/nithinvyas"
    # - name: "github"
    #   url: "https://github.com/arkalim"
    # - name: "cv"
    #   url: "https://drive.google.com/file/d/1U6Gg2RnHSCthtWLbZJBlAEI3V1WGjZty/view"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
